## **Imbalanced Dataset**
A dataset with an unequal class distribution

In [1]:
import pandas as pd
import numpy as np

In [2]:
credit_card_data = pd.read_csv('credit_data.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
# Distribution of the two Classes
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This is highly imbalanced dataset

0 --> Legit Transactions  
1 --> Fraudulent Transactions

In [5]:
# Seperating the Legit and Fraudulent Transactions
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [6]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

### **Undersampling**
Creating a sample dataset containing similar distribution of Legit and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [7]:
# Sample = Give random values from the legit dataframe according to the n
legit_sample = legit.sample(n = 492)

In [8]:
legit_sample.shape

(492, 31)

#### **Concatenate the Two DataFrames**

In [9]:
new_dataset = pd.concat([legit_sample, fraud], axis= 0)

In [10]:
new_dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
48334,43594.0,-0.895281,-0.242367,-0.024588,2.318988,-5.909339,3.560432,5.612854,-1.135219,-1.149863,...,-0.122826,0.860298,0.723655,0.668539,-1.728782,0.830783,0.597089,-0.331641,1269.00,0
215741,140198.0,-0.971857,0.854358,-1.117071,-0.025854,-0.380219,-1.102163,0.551275,0.364053,-0.109911,...,-0.126437,-0.285356,0.684638,-0.045199,-0.568136,-0.661320,-0.469765,-0.142493,93.80,0
239462,150120.0,0.172024,0.862745,-0.842577,-0.888954,1.379611,0.043337,0.751952,0.175309,-0.044903,...,-0.373224,-1.017421,-0.033322,-0.548891,-0.354467,0.163690,0.209272,0.060995,1.29,0
128030,78574.0,-0.591061,1.351384,1.018301,1.938809,-0.167188,-0.322521,0.767952,0.415792,-1.877614,...,-0.231473,-1.085935,0.482809,0.436497,-0.645826,-0.628016,-0.116579,-0.013867,82.56,0
190813,128992.0,-0.998677,0.121941,1.613253,-2.725517,0.213562,-0.339425,0.930472,-0.002130,1.050050,...,-0.370238,-1.098253,-0.072689,0.406036,0.386355,0.204951,-0.016088,-0.112625,76.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [11]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64